AllCops:
  TargetRubyVersion: 2.4
Documentation:
  Enabled: false

Lint/UnusedMethodArgument:
  Enabled: false

Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20

Style/ClassAndModuleChildren:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false